# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: html-to-markdown
  version: "2.0.1"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/html_to_markdown-${{ version }}.tar.gz
  sha256: 33cec38b8b604c2e750e3cea86fc31555553c19b98f48a8b289682934c368a7a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - html-to-markdown = html_to_markdown.__main__:cli
      - html_to_markdown = html_to_markdown.__main__:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - maturin >=1.9,<2
    - tomli >=2
    - pip
  run:
    - python >=${{ python_min }},<4.0

tests:
  - python:
      imports:
        - html_to_markdown
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - html-to-markdown --help
      - html_to_markdown --help

about:
  summary: High-performance HTML to Markdown converter powered by Rust with a clean Python API
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Goldziher/html-to-markdown

extra:
  recipe-maintainers:
    - rxm7706
