# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: html-to-markdown
  version: "2.1.2"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/html_to_markdown-${{ version }}.tar.gz
  sha256: 0fe464bda2247510b1e00de9824a23581e37a22adf8efded315637a17a99297c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - html-to-markdown = html_to_markdown.__main__:cli
      - html_to_markdown = html_to_markdown.__main__:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=78.1
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - beautifulsoup4 >=4.13.4
    - nh3 >=0.2.21

tests:
  - python:
      imports:
        - html_to_markdown
      pip_check: true
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - html-to-markdown --help
      - html_to_markdown --help

about:
  summary: A modern, type-safe Python library for converting HTML to Markdown with comprehensive tag support and customizable options
  homepage: https://github.com/Goldziher/html-to-markdown
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
